### ISSUE TITLE
Cannot access CapX - error message after logging in

### ISSUE THREAD

**Issue by sinnottj-rse** [UoMResearchIT/CapX#179]
I am unable to properly access CapX, either on or off campus. 

I use a managed Mac and can connect to GlobalProtect. On connection, I see the 'your device has passed security checks' message.

I can reach theCapX site and I see the basic page structure with the menu on the left and a 'not authorised' message in the main page area.

I can log in, apparently successfully, but then I'm immediately shown an error page:

![Screenshot 2024-03-12 at 13 26 14](https://github.com/UoMResearchIT/CapX/assets/41161921/4e0079cb-fb8e-4653-9de3-667d19ba6007)

Refreshing the page or clearing all site data and trying again makes no difference.

**Comment by aharwood2** [comment]
Related to #150

**Comment by fherreazcue** [comment]
I get the same error, using chrome on ubuntu, in case that's useful...

**Comment by aharwood2** [comment]
Thanks @fherreazcue -- I'm this is more widespread than just 2 or 3 people but I can't recreate it on my system at the moment which is frustrating. I've just released v1.8.3 and there is some more detailed logging in that version so will see if I can get more of a hint.

**Comment by fherreazcue** [comment]
For what its worth, @ajerrison-manchester  tried on a linux vm and had no issues, but he has different access level as I (or I imagine @sinnottj-rse) do... I imagine @AnjaLeBlanc  would have the same admin view as Andrew, and I don't think she has a problem... 
So it might be worth trying to reproduce having our access level?

**Comment by aharwood2** [comment]
My replication approach was to run locally with a clone of the database then fake the CAS-return with your username so it responds as if you had logged in and I don't get any issue. From what I could see last time I investigated when Mike J reported this, it looks like the DB query is returning no items so the attempts for LINQ to filter the results causes a crash. Given I have more logging in there now, can you try again on this latest version and I will then pull out the logs and post on this thread?

**Comment by sinnottj-rse** [comment]
I've just tried again, but I'm getting the same error message after logging in (Chrome & Safari).  In the browser network log I just see a GET request to https://balex.itservices.manchester.ac.uk/ which fails with a 500 server error.

If it's of any use when searching the logs, my most recent attempt shows the request ID was 00-32133f371ba7b2ce7e666c62adad4d8e-dacf86777723cc6d-00.

**Comment by aharwood2** [comment]
We just did a test on a Linux machine and a "manager" who successfully logged in before gets an error when I downgrade them to "developer" so there is a clue there I think!

**Comment by fherreazcue** [comment]
I was just about to say, we tried yesterday (between 5-6 pm) on my computer to log Anja in, and she could login without issues. 
Hugo, who can normally access from his pc, also tried to login and failed with the same error as me.

This is all on the same computer, same browser, everything... so it must have to do with access level, and it must have to do with linux...

**Comment by sinnottj-rse** [comment]
> This is all on the same computer, same browser, everything... so it must have to do with access level, and it must have to do with linux...

I am using a Mac, so maybe 'not Windows', rather than linux :)

**Comment by aharwood2** [comment]
Not really related to this thread but Firefox users can suffer a performance hit which goes away if you disable the ad blocker. Thought I would note it here.

**Comment by ianhinder** [comment]
Maybe something for the docs?

**Comment by aharwood2** [comment]
Error logs relating to the experiment we tried with @AnjaLeBlanc yesterday and the period of time @fherreazcue and @hidonkey2018 logged in are a mixture of the below and the issue reported at #154.

```
2024-03-27 11:17:19.874 +00:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PPMTool.Services.RolesService.GetAll(PPMToolContext context) in /home/mbgm6ah3/CapX/PPMTool/Services/RolesService.cs:line 32
   at PPMTool.Services.RolesService.GetByUsername(PPMToolContext context, String username) in /home/mbgm6ah3/CapX/PPMTool/Services/RolesService.cs:line 70
   at PPMTool.Pages.Projects.OnInitialized() in /home/mbgm6ah3/CapX/PPMTool/Pages/Projects.razor.cs:line 83
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters)
   at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at PPMTool.Pages.Pages__Host.<ExecuteAsync>b__15_1() in /home/mbgm6ah3/CapX/PPMTool/Pages/_Host.cshtml:line 21
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at PPMTool.Pages.Pages__Host.ExecuteAsync() in /home/mbgm6ah3/CapX/PPMTool/Pages/_Host.cshtml:line 5
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

Doesn't appear to be directly related to @nimpo's issue reported at #150 although there are some similarities in terms of DB queries returning null objects.

**Comment by aharwood2** [comment]
@sinnottj-rse could you try log in at some point today and let me know the time window you tried so I can check if you are having the same issue or whether it is something different?

**Comment by sinnottj-rse** [comment]
> @sinnottj-rse could you try log in at some point today and let me know the time window you tried so I can check if you are having the same issue or whether it is something different?

@aharwood2 I tried at 10:34, with the same error. Hopefully something useful will show up in the logs!

**Comment by aharwood2** [comment]
Looking to role a fix out to production later this afternoon!

**Comment by aharwood2** [comment]
@sinnottj-rse, @hidonkey2018 and @fherreazcue could you try login again at some point and see if the issue has been resolved?

**Comment by sinnottj-rse** [comment]
All working now!

From: Adrian Harwood ***@***.***>
Date: Thursday, 28 March 2024 at 18:20
To: UoMResearchIT/CapX ***@***.***>
Cc: James Sinnott ***@***.***>, Mention ***@***.***>
Subject: Re: [UoMResearchIT/CapX] Cannot access CapX - error message after logging in (Issue #179)

@sinnottj-rse [github.com]<https://urldefense.com/v3/__https:/github.com/sinnottj-rse__;!!PDiH4ENfjr2_Jw!BEX-kXNuEWVuXLMfYjPbyIab6VS8mLckieV1PKJyd1Q-PUQoYgh4qoe0ALtED78m87IgEaqr7K2MbN8JxO7gx0kqJSRQWeqy__nI$>, @hidonkey2018 [github.com]<https://urldefense.com/v3/__https:/github.com/hidonkey2018__;!!PDiH4ENfjr2_Jw!BEX-kXNuEWVuXLMfYjPbyIab6VS8mLckieV1PKJyd1Q-PUQoYgh4qoe0ALtED78m87IgEaqr7K2MbN8JxO7gx0kqJSRQWSah3ixp$> and @fherreazcue [github.com]<https://urldefense.com/v3/__https:/github.com/fherreazcue__;!!PDiH4ENfjr2_Jw!BEX-kXNuEWVuXLMfYjPbyIab6VS8mLckieV1PKJyd1Q-PUQoYgh4qoe0ALtED78m87IgEaqr7K2MbN8JxO7gx0kqJSRQWWrTBQmn$> could you try login again at some point and see if the issue has been resolved?

**Comment by fherreazcue** [comment]
Working for me too :)
