### ISSUE TITLE
Adding a new Innate Code causes a crash

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#318]
Tried to add a new Innate code and DB query crashes:

```
2024-06-20 16:33:00.652 +01:00 [WRN] Unhandled exception rendering component: The LINQ expression 'DbSet<InnateCode>()
    .Any(i => i.GetCodeAsString().ToLower() == __ToLower_0 && i.InnateCodeId != __entity_InnateCodeId_1)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
System.InvalidOperationException: The LINQ expression 'DbSet<InnateCode>()
    .Any(i => i.GetCodeAsString().ToLower() == __ToLower_0 && i.InnateCodeId != __entity_InnateCodeId_1)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at PPMTool.Services.InnateCodeService.DuplicateDetected(PPMToolContext context, InnateCode entity) in /home/mbgm6ah3/CapX/PPMTool/Services/InnateCodeService.cs:line 31
   at PPMTool.Services.InnateCodeService.Add(PPMToolContext context, InnateCode entity) in /home/mbgm6ah3/CapX/PPMTool/Services/InnateCodeService.cs:line 18
   at PPMTool.Pages.DataGridPage`1.OnCreateRow(T entity) in /home/mbgm6ah3/CapX/PPMTool/Pages/DataGridPage.cs:line 80
```

Seen this before, just need to rewrite the Linq query on line 31 of the InnateCodeService.

**Comment by aharwood2** [comment]
Projects, Person and Innate Code Service all use a similar expression so need to test that they all aren't broken.

**Comment by aharwood2** [comment]
We actually need to prevent the add action on the Innate Code page as at the moment it looks like the duplicate code is saved and there is no feedback to the user.

**Comment by aharwood2** [comment]
Fixed by adding status message and overriding behaviours. Checked the person and project service duplicate calls and they seem to be OK.
