### ISSUE TITLE
Crash on adding a new project

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#382]
If I try to add a new project the app crashes when I press Save. I've tried many combinations of different values in the combo boxes but it seems to just crash whatever I put in. The field validation checks have all passed, it is just when committing this to the DB by the look of it.

I've tried the usual logging out and in again, and using a new browser.

The error in the browser console is not that informative, but here it is: 

_Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'._

**Comment by aharwood2** [comment]
Exciting! Will pull the logs later.

**Comment by aharwood2** [comment]
OK. I've looked at the logs and this is a lazy bug introduced by my lack of testing! Will patch CapX over the weekend.

```
2024-07-26 14:15:13.631 +01:00 [ERR] Unhandled exception in circuit 'zTXWSpaq7kTHkko5WStV6aWwhhMJvFzaxJZTEoVRVq4'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PPMTool.Data.Entities.Project.UpdateProjectSummary() in /home/mbgm6ah3/CapX/PPMTool/Data/Entities/Project.cs:line 208
   at PPMTool.Pages.AddProject.HandleSubmit() in /home/mbgm6ah3/CapX/PPMTool/Pages/AddProject.razor.cs:line 162
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
