### ISSUE TITLE
Crash when adding a new tag to a person

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#401]
Created a tag in the DB via the interface. Went to add it to a person and crashed with:

```
2024-08-08 09:48:36.010 +01:00 [ERR] Unhandled exception in circuit 'Ri5Edl2pmHzBrRgNwf17zZ_TXEuOLDfyT_nwDCVUDtY'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PPMTool.Pages.AddPerson.<>c__DisplayClass24_0.<BuildRenderTree>b__19(RenderTreeBuilder __builder3)
   at Radzen.Blazor.RadzenDataListRow`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

Then

```
2024-08-08 09:48:36.019 +01:00 [ERR] Unhandled exception in circuit 'Ri5Edl2pmHzBrRgNwf17zZ_TXEuOLDfyT_nwDCVUDtY'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by aharwood2** [comment]
These errors appear to relate to where the code is accessed from within the HTML on the razor page. Again, I can't reproduce it at the moment so difficult to say where the problem is.

**Comment by aharwood2** [comment]
Found the issue. It was when the number of people with the same tag was displayed on the razor page. If no-one else has the tag then the person list would be null.
