### ISSUE TITLE
Exception when saving project details

### ISSUE THREAD

**Issue by AnjaLeBlanc** [UoMResearchIT/CapX#490]
Starting point was creating/updating: https://balex.itservices.manchester.ac.uk/addproject/253

On hitting the save button: this error appears:
![image](https://github.com/user-attachments/assets/0b19e28e-f288-439f-9035-ff81f0a89cba)

It suggests reloading and clicking on the link in the error message I get:
![image](https://github.com/user-attachments/assets/6c0f40fd-81ab-4010-9ec3-213a3896b2b9)

Error messages from console:
![image](https://github.com/user-attachments/assets/ef94b659-aa62-4046-9a7d-1a15615481d3)

![image](https://github.com/user-attachments/assets/04135891-6adb-4492-bb51-415fdec20a02)

A normal reload of https://balex.itservices.manchester.ac.uk/ works fine again.
I can reproduce above procedure every time I try and I have not actually lost the content of any save operation.

**Comment by aharwood2** [comment]
I can see from the logs that this happened during editing RTP-284. Error is related to some code I changed relating to setting axis limits as part of #474.

```
2024-10-16 10:29:53.609 +01:00 [ERR] Unhandled exception in circuit 'QBzGUjxpS1TuyaBH8q6h8pA3F153Zh052h3qYFXywfw'.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at PPMTool.Pages.ProjectDetails.UpdateScheduleChartAxisLimits() in /home/mbgm6ah3/CapX/PPMTool/Pages/ProjectDetails.razor.cs:line 393
   at PPMTool.Pages.ProjectDetails.OnInitialized() in /home/mbgm6ah3/CapX/PPMTool/Pages/ProjectDetails.razor.cs:line 248
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

**Comment by aharwood2** [comment]
Looks like this happens when there are no tasks in a project -- it tries to redraw the schedule Gantt and fails to set the axis limits. Easy fix. Nothing like testing in production!
