### ISSUE TITLE
Error for newly added projects, unable to edit

### ISSUE THREAD

**Issue by SJaffa** [UoMResearchIT/CapX#507]
I've recently added 2 new projects abd when I try to add or edit tasks it stops responding (it animates when I click on "add task" or "edit task" but doesn't load anything) and shows an error message at the bottom of the screeen prompting me to reload. When I look at any other projects it seems fine.

<img width="1503" alt="Screenshot 2024-10-23 at 10 21 40" src="https://github.com/user-attachments/assets/ab1980f4-dd84-4904-b338-86e09e3894f1">

**Comment by aharwood2** [comment]
From the logs:
```
2024-10-23 10:20:28.513 +01:00 [ERR] Unhandled exception in circuit 'kJxkfkh_jcggShcOO7fLsYm3-_tnT1vwVfbK_ixXGfQ'.
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Decimal.DecCalc.VarDecFromR8(Double input, DecCalc& result)
   at PPMTool.Pages.ProjectDetails.<>c.<BuildRenderTree>b__116_14(ChartItem e) in /home/mbgm6ah3/CapX/PPMTool/Pages/ProjectDetails.razor:line 158
   at ApexCharts.ApexPointSeries`1.<GenerateDataPoints>b__26_0(TItem e)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at ApexCharts.ApexPointSeries`1.GenerateDataPoints(IEnumerable`1 items)
   at ApexCharts.ApexChart`1.SetSeries()
   at ApexCharts.ApexChart`1.PrepareChart()
   at ApexCharts.ApexChart`1.RenderChartAsync()
   at ApexCharts.ApexChart`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
Overflow -- probably due to the date range being "undefined" when there are no tasks yet. Will look at a fix shortly.

**Comment by aharwood2** [comment]
Found the offending line:

```c#
assignments.RoundedSum(task => task.GetPlannedWorkWithinCurrentWeek(currentWeek) * (1 - (task.UnmetDemand / task.Demand)));
```

The problem occurs when the current demand for a task is zero. We get a divide by zero issue!
