### ISSUE TITLE
Sorting by task on Innate Code data grid causes a crash

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#572]
Go to Innate Code admin interface and try sort the data grid by the task. As this is using a custom template and some entries are null it causes a crash.

**Comment by aharwood2** [comment]
Get this in the error log:
```
System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
   at System.Linq.EnumerableSorter`2.CompareAnyKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`2.PartialQuickSort(Int32[] map, Int32 left, Int32 right, Int32 minIdx, Int32 maxIdx)
   at System.Linq.OrderedEnumerable`1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Radzen.PagedDataBoundComponent`1.get_PagedView()
   at Radzen.Blazor.RadzenDataGrid`1.DrawGroupOrDataRows(RenderTreeBuilder builder, IList`1 visibleColumns)
   at Radzen.Blazor.RadzenDataGrid`1.<>c__DisplayClass20_0.<DrawRows>b__0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Radzen.Blazor.RadzenDataGrid`1.<BuildRenderTree>b__658_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by aharwood2** [comment]
This is because the field referenced is a collection. Radzen data grids do not support sorting on a collection. So we have to disable the sortable property. We could do the filtering manually by filtering the datagrid source but I'm not sure why we need to.

**Comment by aharwood2** [comment]
See https://forum.radzen.com/t/datagrid-with-multiple-elements-for-column-will-not-sort-or-filter/14451
