### ISSUE TITLE
Crash viewing project details after adding a fixed work task with zero demand

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#612]
As reported by @AnnAnnFryingPan.

Error log:
```
2024-12-03 15:54:34.155 +00:00 [ERR] Unhandled exception in circuit 'ReQHuuNjc9fEBRkDF8z7p9g00ktlRdhqiJdpxdsIihY'.
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Decimal.DecCalc.VarDecFromR8(Double input, DecCalc& result)
   at PPMTool.Pages.ProjectDetails.<>c.<BuildRenderTree>b__116_13(ChartItem e) in /home/mbgm6ah3/CapX/PPMTool/Pages/ProjectDetails.razor:line 152
   at ApexCharts.ApexPointSeries`1.<GenerateDataPoints>b__26_0(TItem e) in /home/mbgm6ah3/CapX/Blazor-ApexCharts/src/Blazor-ApexCharts/Series/ApexPointSeries.cs:line 105
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at ApexCharts.ApexPointSeries`1.GenerateDataPoints(IEnumerable`1 items) in /home/mbgm6ah3/CapX/Blazor-ApexCharts/src/Blazor-ApexCharts/Series/ApexPointSeries.cs:line 130
   at ApexCharts.ApexChart`1.SetSeries() in /home/mbgm6ah3/CapX/Blazor-ApexCharts/src/Blazor-ApexCharts/ApexChart.razor.cs:line 1274
   at ApexCharts.ApexChart`1.PrepareChart() in /home/mbgm6ah3/CapX/Blazor-ApexCharts/src/Blazor-ApexCharts/ApexChart.razor.cs:line 1096
   at ApexCharts.ApexChart`1.RenderChartAsync() in /home/mbgm6ah3/CapX/Blazor-ApexCharts/src/Blazor-ApexCharts/ApexChart.razor.cs:line 1235
   at ApexCharts.ApexChart`1.OnAfterRenderAsync(Boolean firstRender) in /home/mbgm6ah3/CapX/Blazor-ApexCharts/src/Blazor-ApexCharts/ApexChart.razor.cs:line 439
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Although I thought it was solved by #510 (reported in #507), this is an adjacent issue with the same consequence.

**Comment by aharwood2** [comment]
Issue is caused by adding a new task with zero demand, the end date never gets updated with fixed work scheduling so the task has a duration of zero. Later this is used as a divisor and hence we get an overflow when trying to cast the resulting value to a decimal when plotting the values for the burn-up chart.

**Comment by aharwood2** [comment]
I've going to change the logic so that a) if someone genuinely wants a demand of zero, the task just uses the original demand to schedule itself -- it will have unmet demand of zero and no resources so it should cause any issues doing this. b) We should provide a warning popup when saving so that the user knows they have zero demand set.
